apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://blakeblackshear.github.io/blakeshome-charts/'
    targetRevision: 7.1.0
    chart: frigate
    helm:
      releaseName: frigate
      values: |
        coral:
          enabled: true
        config: |
          mqtt:
            enabled: false
          cameras:
            front:
              ffmpeg:
                inputs:
                  - path: rtsp://streamer:Stinkles@192.168.0.7/Streaming/channels/101
                    roles:
                      - detect
                      - rtmp
              detect:
                width: 1280
                height: 720
        service:
          port: 80
          type: LoadBalancer
        persistence:
          data:
            size: 10Gi
            enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: frigate
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
