apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    name: 'in-cluster'
    namespace: metallb
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: '*'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
      syncOptions:
      - RespectIgnoreDifferences=true
