apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    name: 'in-cluster'
    namespace: metallb
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: '*'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
