apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: "*"
    chart: pihole
    releaseName: pihole
    helm:
      values: |
        serviceWeb:
          loadBalancerIP: 192.168.0.205
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
        serviceDns:
          loadBalancerIP: 192.168.0.205
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
        podDnsConfig:
          enabled: true
          policy: "None"
          nameservers:
          - 8.8.8.8
          - 1.1.1.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pihole
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
