apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
spec:
  destination:
    name: 'in-cluster'
    namespace: plex
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    chart: plex-media-server
    targetRevision: '*'
    helm:
      releaseName: plex
      parameters:
      values: |
        ingress:
          enabled: false
        pms:
          configStorage: 10Gi
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
